### ISSUE TITLE
Problems with graphviz lib

### ISSUE THREAD

**Issue by dimitrymindlin** [bach1292/XAGENT#1]
Hey,

I am not sure which version of graphviz you use. From your environment.yml I see "python-graphviz==0.16" under the pip packages. Yet there is no python-graphviz for pip when I try to install or google it. [I can find it for conda](https://anaconda.org/conda-forge/python-graphviz) but when I move it up to the conda requirements, I get a lot of dependency conflicts. And when installing [graphviz via pip](https://pypi.org/project/graphviz/) I get the following error when executing the second cell in the jupyter notebooks:

```
ImportError                               Traceback (most recent call last)
<ipython-input-2-a3c4be778a53> in <module>
      5 import matplotlib
      6 import numpy as np
----> 7 from Agent import agent
      8 import matplotlib.pyplot as plt
      9 

~/UniProjects/XAGENT/XAgent/Agent/agent.py in <module>
     20 from sklearn.pipeline import Pipeline
     21 from sklearn.preprocessing import OneHotEncoder
---> 22 from Agent.answer import Answers
     23 from Agent import utils
     24 from anchor import anchor_tabular

~/UniProjects/XAGENT/XAgent/Agent/answer.py in <module>
      3 
      4 import shap
----> 5 from dtreeviz.trees import *
      6 
      7 # print the JS visualization code to the notebook

~/miniconda3-intel/envs/xagent/lib/python3.8/site-packages/dtreeviz/__init__.py in <module>
      1 from .version import __version__
      2 
----> 3 from dtreeviz.classifiers import clfviz

~/miniconda3-intel/envs/xagent/lib/python3.8/site-packages/dtreeviz/classifiers.py in <module>
      9 
     10 from dtreeviz.colors import adjust_colors, GREY
---> 11 from dtreeviz.trees import add_classifier_legend
     12 from dtreeviz import utils
     13 

~/miniconda3-intel/envs/xagent/lib/python3.8/site-packages/dtreeviz/trees.py in <module>
     11 import matplotlib.pyplot as plt
     12 from colour import Color, rgb2hex
---> 13 from graphviz.backend import run, view
     14 from sklearn import tree
     15 from typing import Mapping, List, Tuple

ImportError: cannot import name 'run' from 'graphviz.backend' (/Users/*/miniconda3-intel/envs/xagent/lib/python3.8/site-packages/graphviz/backend/__init__.py)
```

I am working on a mac if that makes any difference.
Happy to hear from you!
Dimi

**Comment by bach1292** [comment]
Hi Dimi,

thank you for your valuable feedbacks!
Indeed, the package should be graphviz==0.16 instead of python-graphviz==0.16. I updated the environment.yml file to fix this issue.
About the error, I couldn't reproduce it after installing graphviz==0.16 (I used Mac as well). Could you check your graphviz version?

Best regards,
Bach

**Comment by dimitrymindlin** [comment]
Hey Bach,

thank you for clarification. I guess I forgot to include the version number when I tried the different options. This error is gone yet the same line of code now makes the Kernel Restart.

<img width="726" alt="image" src="https://user-images.githubusercontent.com/25254873/193621123-3b083350-87bd-40f7-a90f-5429a6f3ef5c.png">

Did you ever experience that? 
I do now know if it is still related to graphviz since I do not get any error log and the jupyter restarts.

Its the Line:

`from Agent.agent import Agent`

Happy to hear from you!

Kind regards,

Dimi

**Comment by bach1292** [comment]
Hi Dimi,

I checked it again (re-installed everything from beginning) and couldn't reproduce the problem on my machine. It took a while to import the agent, but finally, it worked well. Can you check again with a different machine?(more powerful machine might be better) 

Best regards,
Bach
